USE manfeng_game_test;
DELETE FROM game_user;
INSERT INTO game_user VALUES (NULL,'GM','1234','True',NULL);
INSERT INTO game_user VALUES (NULL,'Megan','F','True',NULL);
INSERT INTO game_user VALUES (NULL,'Joseph','M','False',NULL);
INSERT INTO game_user VALUES (NULL,'Kyle','M','True',NULL);
INSERT INTO game_user VALUES (NULL,'Katie','F','True',NULL);
INSERT INTO game_user VALUES (NULL,'Abby','F','True',NULL);
INSERT INTO game_user VALUES (NULL,'Nathan','M','True',NULL);
INSERT INTO game_user VALUES (NULL,'Liesl','F','True',NULL);
INSERT INTO game_user VALUES (NULL,'Ian','M','True',NULL);
INSERT INTO game_user VALUES (NULL,'Colin','M','False',NULL);
INSERT INTO game_user VALUES (NULL,'Peter','M','True',NULL);
INSERT INTO game_user VALUES (NULL,'Michael','M','True',NULL);
INSERT INTO game_user VALUES (NULL,'Thomas','M','True',NULL);
INSERT INTO game_user VALUES (NULL,'Devri','F','True',NULL);
INSERT INTO game_user VALUES (NULL,'Ben','M','True',NULL);
INSERT INTO game_user VALUES (NULL,'Aubrey','F','True',NULL);
INSERT INTO game_user VALUES (NULL,'Rebecca','F','True',NULL);