USE manfeng_game_test;
DELETE FROM system_user_table;
INSERT INTO system_user_table VALUES (NULL,'Megan','F','Member','True',NULL);
INSERT INTO system_user_table VALUES (NULL,'Joseph','M','Normal','True',NULL);
INSERT INTO system_user_table VALUES (NULL,'Kyle','M','Normal','True',NULL);
INSERT INTO system_user_table VALUES (NULL,'Katie','F','Member','False',NULL);
INSERT INTO system_user_table VALUES (NULL,'Abby','1234','Super','True',NULL);
INSERT INTO system_user_table VALUES (NULL,'Nathan','M','Normal','True',NULL);
INSERT INTO system_user_table VALUES (NULL,'Liesl','F','Normal','False',NULL);
INSERT INTO system_user_table VALUES (NULL,'Ian','M','Member','True',NULL);
INSERT INTO system_user_table VALUES (NULL,'Colin','M','Normal','False',NULL);
INSERT INTO system_user_table VALUES (NULL,'Peter','M','Normal','True',NULL);
INSERT INTO system_user_table VALUES (NULL,'Michael','M','Normal','True',NULL);
INSERT INTO system_user_table VALUES (NULL,'Thomas','M','Normal','True',NULL);
INSERT INTO system_user_table VALUES (NULL,'Devri','F','Normal','True',NULL);
INSERT INTO system_user_table VALUES (NULL,'Ben','M','Normal','True',NULL);
INSERT INTO system_user_table VALUES (NULL,'Aubrey','F','Normal','True',NULL);
INSERT INTO system_user_table VALUES (NULL,'Rebecca','F','Normal','True',NULL);